export default [
  {
    user_id: 401,
    email_id: "john.doe@example.com",
    password: "hashedpassword1",
    first_name: "John",
    last_name: "Doe",
    phone_no: "555-123-4567",
    street: "123 Elm Street",
    city: "Toronto",
    province: "Ontario",
    country: "Canada",
    zipcode: "A1B 2C3",
    image_url: "john_doe.jpg",
  },
  {
    user_id: 402,
    email_id: "jane.smith@example.com",
    password: "hashedpassword2",
    first_name: "Jane",
    last_name: "Smith",
    phone_no: "555-234-5678",
    street: "456 Oak Avenue",
    city: "Vancouver",
    province: "British Columbia",
    country: "Canada",
    zipcode: "D4E 5F6",
    image_url: "jane_smith.jpg",
  },
  {
    user_id: 403,
    email_id: "michael.brown@example.com",
    password: "hashedpassword3",
    first_name: "Michael",
    last_name: "Brown",
    phone_no: "555-345-6789",
    street: "789 Pine Road",
    city: "Montreal",
    province: "Quebec",
    country: "Canada",
    zipcode: "G7H 8I9",
    image_url: "michael_brown.jpg",
  },
  {
    user_id: 404,
    email_id: "emily.johnson@example.com",
    password: "hashedpassword4",
    first_name: "Emily",
    last_name: "Johnson",
    phone_no: "555-456-7890",
    street: "321 Maple Boulevard",
    city: "Calgary",
    province: "Alberta",
    country: "Canada",
    zipcode: "J1K 2L3",
    image_url: "emily_johnson.jpg",
  },
  {
    user_id: 405,
    email_id: "david.wilson@example.com",
    password: "hashedpassword5",
    first_name: "David",
    last_name: "Wilson",
    phone_no: "555-567-8901",
    street: "654 Cedar Lane",
    city: "Ottawa",
    province: "Ontario",
    country: "Canada",
    zipcode: "M4N 3O6",
    image_url: "david_wilson.jpg",
  },
  {
    user_id: 406,
    email_id: "sophia.miller@example.com",
    password: "hashedpassword6",
    first_name: "Sophia",
    last_name: "Miller",
    phone_no: "555-678-9012",
    street: "987 Birch Circle",
    city: "Halifax",
    province: "Nova Scotia",
    country: "Canada",
    zipcode: "P1Q 4R5",
    image_url: "sophia_miller.jpg",
  },
  {
    user_id: 407,
    email_id: "daniel.davis@example.com",
    password: "hashedpassword7",
    first_name: "Daniel",
    last_name: "Davis",
    phone_no: "555-789-0123",
    street: "234 Spruce Drive",
    city: "Winnipeg",
    province: "Manitoba",
    country: "Canada",
    zipcode: "S6T 7U8",
    image_url: "daniel_davis.jpg",
  },
  {
    user_id: 408,
    email_id: "olivia.thompson@example.com",
    password: "hashedpassword8",
    first_name: "Olivia",
    last_name: "Thompson",
    phone_no: "555-890-1234",
    street: "567 Fir Way",
    city: "Edmonton",
    province: "Alberta",
    country: "Canada",
    zipcode: "T9A 0B1",
    image_url: "olivia_thompson.jpg",
  },
  {
    user_id: 409,
    email_id: "james.white@example.com",
    password: "hashedpassword9",
    first_name: "James",
    last_name: "White",
    phone_no: "555-901-2345",
    street: "890 Walnut Terrace",
    city: "Victoria",
    province: "British Columbia",
    country: "Canada",
    zipcode: "V8W 3C2",
    image_url: "james_white.jpg",
  },
  {
    user_id: 410,
    email_id: "isabella.harris@example.com",
    password: "hashedpassword10",
    first_name: "Isabella",
    last_name: "Harris",
    phone_no: "555-012-3456",
    street: "135 Chestnut Place",
    city: "St. John's",
    province: "Newfoundland and Labrador",
    country: "Canada",
    zipcode: "A1C 1A1",
    image_url: "isabella_harris.jpg",
  },
];
